### ISSUE TITLE
slight change in Windcube200s netcdf format (reference time) with new software (21.c)

### ISSUE THREAD

**Issue by StevenKnoopKNMI** [jdiasn/lidarwind#110]
* LIDAR Suit version: older lidarsuit version
* Python version: 
* Operating System: windows and linux

### Description

With a new software on the Windcube200S instrument, the format of the netcdf output data has changed regarding the time variable. The time reference is now more explicit, which impacts the way the lidarwind package reads in those netcdf files. Only a minor change to io.py has to be made.

### What I Did

```
    raw_data = datatree.open_datatree(file_name, decode_times=False)

    assert (
        "sweep_group_name" in raw_data
    ), "missing sweep group variable in input file"
    sweep_group_name = raw_data["sweep_group_name"].values[0]
    ds = raw_data[f"/{sweep_group_name}"].to_dataset()

    if "time_reference" in ds:
        assert "time_reference" in ds, "missing time_reference in input sweep"
        # Guarantee that it is a valid datetime
        reference_time = pd.to_datetime(ds["time_reference"].values).isoformat()
        ds["time"].attrs["units"] = f"seconds since {reference_time}"

    else:
        assert "timestamp" in ds, "missing timestamp in input sweep"


    ds = xr.decode_cf(ds)

    return ds
```

I propose to add a if .. else statement in io.py to be compatible with data coming from both netcdf formats. "time_reference" is a variable in the older sofware, but in the newer it is not there, while a time reference is already provided explicitly, so we can omit this step with the newer software. This works with my local lidarSuit software.

**Comment by jdiasn** [comment]
Thank you, @StevenKnoopKNMI. I am implementing your suggestion.
