### ISSUE TITLE
[JOSS Review]: package name not following PEP8 and might be misleading

### ISSUE THREAD

**Issue by tgoelles** [jdiasn/lidarwind#49]
Similar to issue #48 

Consider renaming the package. You shouldn't use camel case there.
Also I think that lidarSuit is not really a suitable name, since lidar is so much more and wind lidar is just a smaller part if it.
The name should be short and meaningful.

I suggest :
windcube or windlidar 

In some text you write about lidar_suit. Please, keep it consistent.

This is just a suggestion and I think you would benefit from it since its draws in the right people.

https://github.com/openjournals/joss-reviews/issues/4852

**Comment by jdiasn** [comment]
@tgoelles, thank you for pointing this out. We are going to remove the camel case and re-think the package name.

**Comment by jdiasn** [comment]
@tgoelles, the package was renamed, and the new name is lidarwind. I reviewed the entire package, and all wrong usage of the camel case was fixed.  I think I completed all issues from this PR. If you agree with it you can close this PR.

**Comment by tgoelles** [comment]
Yes the new name is good and camel case is gone.

https://pypi.org/classifiers/

Just an additional hint to improve the pypi page:

https://pypi.org/classifiers/ 

and use the readme in the long_description in setup.py

**Comment by jdiasn** [comment]
Thank you, @tgoelles! I will look at those additional points to further improve the package.
