### ISSUE TITLE
[JOSS review] Comments

### ISSUE THREAD

**Issue by acocac** [jdiasn/lidarwind#53]
* LIDAR Suit version: 0.1.6 
* Python version: 3.8
* Operating System: Mac OS

# 
Dear authors,

Thanks for the submission of the paper. I've found very interesting the contribution, proposed features and efforts to building upon existing open-source python packages for handling N-dimensional datasets e.g. `xarray`. Please find below general and minor comments. Also, I've posted my overall comments in the paper [REVIEW](https://github.com/openjournals/joss-reviews/issues/4852).

# General
- ~~The documentation would benefit from adding more details of `lidarSuit`. There is only a short description of how to generate a config file, however notebooks describe key functions i.e. `sixBeamMethod`, `dbsOperations`, etc.~~ 
- ~~The `notebook` folder is located within the `docs` dir. I would suggest moving it to the root dir. Also, you can create a section of rendered notebooks in the documentation.~~
-  ~~I think the paper is clear and well written. It would be great to add a diagram of the architecture of the library (flowchart and class hierarchy of the package). You could point into the same diagram future developments e.g. computing the Reynold stress for the VAD and DBS. Also, for non-experts it would be helpful to include some visualisation outputs with a brief interpretation.~~ 
- Binder link doesn’t work (Failed to connect to event stream).
- ~~Typos in README, luidarSuit, 6-bean.~~
- Add a short and more accessible How to Contribute in README. 

# Others (optional):
- ~~The package name should be changed as it focuses only on wind lidar.~~
- ~~Google drive is not the most reliable storage for sample data. I suggest using Zenodo or another platform alike. There are some handy python open-source packages to handle files in Zenodo. For instance, the [pooch](https://github.com/fatiando/pooch) package enforces that everyone running the code has the same version of the data files (through the SHA256 hashes).~~

**Comment by jdiasn** [comment]
@acocac Thank you for your review! Your suggestions were very interesting and important for the further development of the package. We will be working to incorporate those suggestions and will let you know as soon as they are implemented.

**Comment by jdiasn** [comment]
@acocac,  I believe I addressed all issues listed here. The notebooks were expanded to improve the usage description, and a section of rendered notebooks was added to the documentation (https://lidarwind.readthedocs.io/en/latest/notebooks.html). The usage section of the documentation was expanded to explain how the package can be used for pre-processing the data and retrieving winds from the different scanning strategies. A section introducing the different scanning strategies and how the wind is retrieved was also added to the documentation (https://lidarwind.readthedocs.io/en/latest/overview.html). The package was renamed. The sample data was moved to Zenodo, and the notebook examples are using pooch to download the data.  The wind field retrieved from a particular day was added to the paper, but the diagram was only added to the documentation.


If you think all points listed in this issue were addressed, you can close this issue.

**Comment by acocac** [comment]
@jdiasn thanks for addressing my comments. All implemented changes look good to me. It's ok to include the diagram in the documentation instead of the manuscript. Also, the figure of wind field retrieval is a great example and it was nicely explained with a plain language.

My only comment is regarding the Binder. Considering the relevance of this resource, I suggest to update the following text within [DBS data wind retrieval](https://lidarwind.readthedocs.io/en/latest/usage.html?highlight=binder#dbs-data-wind-retrieval) and [6-beam data wind retrieval](https://lidarwind.readthedocs.io/en/latest/usage.html?highlight=binder#beam-data-wind-retrieval) notebooks. Also the Binder doens't work due to conflicts with the lidarversion:

```
ERROR: Could not find a version that satisfies the requirement lidarwind==0.1.6 (from versions: 0.2.1)
ERROR: No matching distribution found for lidarwind==0.1.6
```

I strongly encourage you to address the issue. Binder would facilitate potential users to run and explore your package. If it's ok I'll open a new issue and then you close it at your earliest convenience.
