### ISSUE TITLE
[JOSS Review]: minor issues

### ISSUE THREAD

**Issue by tgoelles** [jdiasn/lidarwind#54]
# Minor issues

* A lot of commented code needs to be deleted. That's what version control is for.
* look up f-strings. Makes the code more readable. You don't need to change your code, but just a hint for the future

## Documenation
* you have a docstring in the methods. Let Sphinx generate the html documentation from it and include it in readthedocs
* add the API reference to the sidebar menu (Contents)

## jupyter notebooks

* why use uncomment in cells in the jupyter notebooks? Just delete the output cells before saving. You could use nbstripout for that
* quicklooks.ipynb did not work: FileNotFoundError
* turbulence_6beam_data.ipyn did not work: FileNotFoundError
* you should add the notebooks to the test suite:  pytest --cov-append --current-env --nbval-lax xxxxx.ipynb (this only checks if the cells evaluated without error)

## Paper

* use Python not python in the paper
* cite NetCDF: <https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg00087.html>

https://github.com/openjournals/joss-reviews/issues/4852

**Comment by jdiasn** [comment]
@tgoelles Thank you again for your suggestions! They are very interesting and cover points that I had missed during the development.

**Comment by jdiasn** [comment]
Hi @tgoelles, I believe I addressed all points you listed here. 
I managed to add the docstrings to the readthedocs (https://lidarwind.readthedocs.io/en/latest/modules.html). That was a really nice suggestion.

**Comment by tgoelles** [comment]
Hi, 

I would still add nbval to the tests
https://pypi.org/project/nbval/ 

But if you dont want to its also fine.
